"""
_mocks/mock_props.py
Fake prop data for local testing without API keys.
"""

MOCK_PLAYS = [
    {
        "player": "Corbin Burnes",
        "team": "Arizona Diamondbacks",
        "opponent": "Los Angeles Dodgers",
        "sport": "baseball_mlb",
        "sport_label": "MLB",
        "prop_label": "Strikeouts",
        "icon": "⚾",
        "line": 7.5,
        "over_odds": -115,
        "under_odds": -105,
        "implied_prob": 0.535,
        "bookmaker": "DraftKings",
        "commence_time": "2025-04-15T18:10:00Z",
        "fetched_at": "2025-04-15T12:00:00Z",
        "sim_prob": 0.622,
        "edge": 0.087,
        "grade": "A+",
        "confidence_score": 91,
        "play_label": "Precision Play",
        "display_line": "OVER 7.5",
        "display_odds": "-115",
    },
    {
        "player": "Stephen Curry",
        "team": "Golden State Warriors",
        "opponent": "Houston Rockets",
        "sport": "basketball_nba",
        "sport_label": "NBA",
        "prop_label": "3-Pointers",
        "icon": "🏀",
        "line": 4.5,
        "over_odds": -110,
        "under_odds": -110,
        "implied_prob": 0.524,
        "bookmaker": "FanDuel",
        "commence_time": "2025-04-15T19:30:00Z",
        "fetched_at": "2025-04-15T12:00:00Z",
        "sim_prob": 0.591,
        "edge": 0.067,
        "grade": "A",
        "confidence_score": 90,
        "play_label": "Sharp Play",
        "display_line": "OVER 4.5",
        "display_odds": "-110",
    },
    {
        "player": "Nathan MacKinnon",
        "team": "Colorado Avalanche",
        "opponent": "Vegas Golden Knights",
        "sport": "icehockey_nhl",
        "sport_label": "NHL",
        "prop_label": "Shots on Goal",
        "icon": "🏒",
        "line": 3.5,
        "over_odds": -120,
        "under_odds": 100,
        "implied_prob": 0.545,
        "bookmaker": "BetMGM",
        "commence_time": "2025-04-15T20:00:00Z",
        "fetched_at": "2025-04-15T12:00:00Z",
        "sim_prob": 0.591,
        "edge": 0.046,
        "grade": "A-",
        "confidence_score": 88,
        "play_label": "Sharp Play",
        "display_line": "OVER 3.5",
        "display_odds": "-120",
    },
]
